/*
 * =========================================================================
 *  Copyright (C)2018 NCS Pte. Ltd. All Rights Reserved
 *
 *  This software is confidential and proprietary to NCS Pte. Ltd. You shall
 *  use this software only in accordance with the terms of the license
 *  agreement you entered into with NCS.  No aspect or part or all of this
 *  software may be reproduced, modified or disclosed without full and
 *  direct written authorisation from NCS.
 *
 *  NCS SUPPLIES THIS SOFTWARE ON AN "AS IS" BASIS. NCS MAKES NO
 *  REPRESENTATIONS OR WARRANTIES, EITHER EXPRESSLY OR IMPLIEDLY, ABOUT THE
 *  SUITABILITY OR NON-INFRINGEMENT OF THE SOFTWARE. NCS SHALL NOT BE LIABLE
 *  FOR ANY LOSSES OR DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
 *  MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 *  =========================================================================
 */
/**
 * Created by xulu on 25/05/2018.
 */
export const TOPOMGMTFLOATTAB_INIT = "TOPOMGMTFLOATTAB/INIT";
export const TOPOMGMTFLOATTAB_SET = "TOPOMGMTFLOATTAB/SET";
export const TOPOMGMTFLOATTAB_CHANGETAB = "TOPOMGMTFLOATTAB/CHANGETAB";

export const TOPOMGMTFLOATTAB_GETDETAIL = "TOPOMGMTFLOATTAB/GETDETAIL";
export const TOPOMGMTFLOATTAB_GETDETAIL_SUCCESS = "TOPOMGMTFLOATTAB/GETDETAIL_SUCCESS";

export const TOPOMGMTFLOATTAB_GETALARM = "TOPOMGMTFLOATTAB/GETALARM";
export const TOPOMGMTFLOATTAB_GETALARM_SUCCESS = "TOPOMGMTFLOATTAB/GETALARM_SUCCESS";

export const TOPOMGMTFLOATTAB_GETEVENT = "TOPOMGMTFLOATTAB/GETEVENT";
export const TOPOMGMTFLOATTAB_GETEVENT_SUCCESS = "TOPOMGMTFLOATTAB/GETEVENT_SUCCESS";

export const TOPOMGMTFLOATTAB_DETAIL_SEARCH = "TOPOMGMTFLOATTAB/DETAIL_SEARCH";

export const TOPOMGMTFLOATTAB_SET_TITLE = "TOPOMGMTFLOATTAB/SET_TITLE";

// search topo type
export const TOPOMGMTFLOATTAB_SEARCH_TOPOTYPE = "TOPOMGMTFLOATTAB/SEARCH_TOPOTYPE";
export const TOPOMGMTFLOATTAB_SEARCH_TOPOTYPE_SUCCESS = "TOPOMGMTFLOATTAB/SEARCH_TOPOTYPE_SUCCESS";

// select device type when add new device
export const TOPOMGMTFLOATTAB_SELECT_DEVICE_TYPE = "TOPOMGMTFLOATTAB/SELECT_DEVICE_TYPE";

// search topology address
export const TOPOMGMTFLOATTAB_SEARCH_ADDRESS = "TOPOMGMTFLOATTAB/SEARCH_ADDRESS";
export const TOPOMGMTFLOATTAB_SEARCH_ADDRESS_SUCCESS = "TOPOMGMTFLOATTAB/SEARCH_ADDRESS_SUCCESS";

// search topology address
export const TOPOMGMTFLOATTAB_SEARCH_LOCATION = "TOPOMGMTFLOATTAB/SEARCH_LOCATION";
export const TOPOMGMTFLOATTAB_SEARCH_LOCATION_SUCCESS = "TOPOMGMTFLOATTAB/SEARCH_LOCATION_SUCCESS";

// add device
export const TOPOMGMTFLOATTAB_ADD_DEVICE = "TOPOMGMTFLOATTAB/ADD_DEVICE";
export const TOPOMGMTFLOATTAB_ADD_DEVICE_SUCCESS = "TOPOMGMTFLOATTAB/ADD_DEVICE_SUCCESS";

// change add device stepper
export const TOPOMGMTFLOATTAB_CHANGE_AVTIVESTEP = "TOPOMGMTFLOATTAB/CHANGE_AVTIVESTEP";

// get device schema
export const TOPOMGMTFLOATTAB_GET_DEVICE_SCHEMA = "TOPOMGMTFLOATTAB/GET_DEVICE_SCHEMA";
export const TOPOMGMTFLOATTAB_GET_DEVICE_SCHEMA_SUCCESS = "TOPOMGMTFLOATTAB/GET_DEVICE_SCHEMA_SUCCESS";

export const TOPOMGMTFLOATTAB_GET_DEVICE_TYPE_SCHEMA = "TOPOMGMTFLOATTAB/GET_DEVICE_TYPE_SCHEMA_SUCCESS";

// add device type
export const TOPOMGMTFLOATTAB_ADD_DEVICE_TYPE = "TOPOMGMTFLOATTAB/ADD_DEVICE_TYPE";
export const TOPOMGMTFLOATTAB_ADD_DEVICE_TYPE_SUCCESS = "TOPOMGMTFLOATTAB/ADD_DEVICE_TYPE_SUCCESS";

// add device type to sysconfig
export const TOPOMGMTFLOATTAB_ADD_DEVICE_TYPE_SYSCONFIG = "TOPOMGMTFLOATTAB/ADD_DEVICE_TYPE_SYSCONFIG";
export const TOPOMGMTFLOATTAB_ADD_DEVICE_TYPE_SYSCONFIG_SUCCESS = "TOPOMGMTFLOATTAB/ADD_DEVICE_TYPE_SYSCONFIG_SUCCESS";

// get sysconfig basic types
export const TOPOMGMTFLOATTAB_GET_SYSCONFIG_BASIC_TYPE = "TOPOMGMTFLOATTAB/GET_SYSCONFIG_BASIC_TYPE";
export const TOPOMGMTFLOATTAB_GET_SYSCONFIG_BASIC_TYPE_SUCCESS = "TOPOMGMTFLOATTAB/GET_SYSCONFIG_BASIC_TYPE_SUCCESS";

// choose icon
export const TOPOMGMTFLOATTAB_CHOOSE_ICON = "TOPOMGMTFLOATTAB/CHOOSE_ICON";

// get device type detail
export const TOPOMGMTFLOATTAB_GET_DEVICE_TYPE_DETAIL = "TOPOMGMTFLOATTAB/GET_DEVICE_TYPE_DETAIL";
export const TOPOMGMTFLOATTAB_GET_DEVICE_TYPE_DETAIL_SUCCESS = "TOPOMGMTFLOATTAB/GET_DEVICE_TYPE_DETAIL_SUCCESS";

// get sysconfig device type detail
export const TOPOMGMTFLOATTAB_GET_SYSCONFIG_DEVICE_TYPE_DETAIL = "TOPOMGMTFLOATTAB/GET_SYSCONFIG_DEVICE_TYPE_DETAIL";
export const TOPOMGMTFLOATTAB_GET_SYSCONFIG_DEVICE_TYPE_DETAIL_SUCCESS =
    "TOPOMGMTFLOATTAB/GET_SYSCONFIG_DEVICE_TYPE_DETAIL_SUCCESS";

// edit device detail
export const TOPOMGMTFLOATTAB_EDIT_DEVICE_DETAIL = "TOPOMGMTFLOATTAB/EDIT_DEVICE_DETAIL";
export const TOPOMGMTFLOATTAB_EDIT_DEVICE_DETAIL_SUCCESS = "TOPOMGMTFLOATTAB/EDIT_DEVICE_DETAIL_SUCCESS";

// property change when add device type
export const TOPOMGMTFLOATTAB_PROPERTY_CHANGE = "TOPOMGMTFLOATTAB/PROPERTY_CHANGE";

export const TOPOMGMTFLOATTAB_DELETE_DEVICE_TYPE = "TOPOMGMTFLOATTAB/DELETE_DEVICE_TYPE";

// add device type property
export const TOPOMGMTFLOATTAB_ADD_DEVICE_TYPE_PROPERTY = "TOPOMGMTFLOATTAB/ADD_DEVICE_TYPE_PROPERTY";

// add device location
export const TOPOMGMTFLOATTAB_ADD_LOCATION = "TOPOMGMTFLOATTAB/ADD_LOCATION";
export const TOPOMGMTFLOATTAB_ADD_LOCATION_SUCCESS = "TOPOMGMTFLOATTAB/ADD_LOCATION_SUCCESS";

// edit device type
export const TOPOMGMTFLOATTAB_EDIT_DEVICE_TYPE = "TOPOMGMTFLOATTAB/EDIT_DEVICE_TYPE";
export const TOPOMGMTFLOATTAB_EDIT_DEVICE_TYPE_SUCCESS = "TOPOMGMTFLOATTAB/EDIT_DEVICE_TYPE_SUCCESS";

// edit device type to sysconfig
export const TOPOMGMTFLOATTAB_EDIT_DEVICE_TYPE_SYSCONFIG = "TOPOMGMTFLOATTAB/EDIT_DEVICE_TYPE_SYSCONFIG";
export const TOPOMGMTFLOATTAB_EDIT_DEVICE_TYPE_SYSCONFIG_SUCCESS =
    "TOPOMGMTFLOATTAB/EDIT_DEVICE_TYPE_SYSCONFIG_SUCCESS";

// add application
export const TOPOMGMTFLOATTAB_CREATE_APP = "TOPOMGMTFLOATTAB/CREATE_APP";
export const TOPOMGMTFLOATTAB_CREATE_APP_SUCCESS = "TOPOMGMTFLOATTAB/CREATE_APP_SUCCESS";

// get app schema
export const TOPOMGMTFLOATTAB_GETAPP_SCHEMA_REQUEST = "TOPOMGMTFLOATTAB/GETAPP_SCHEMA_REQUEST";
export const TOPOMGMTFLOATTAB_GETAPP_SCHEMA_SUCCESS = "TOPOMGMTFLOATTAB/GETAPP_SCHEMA_SUCCESS";

// add application location
export const TOPOMGMTFLOATTAB_ADD_APP_LOCATION = "TOPOMGMTFLOATTAB/ADD_APP_LOCATION";
export const TOPOMGMTFLOATTAB_ADD_APP_LOCATION_SUCCESS = "TOPOMGMTFLOATTAB/ADD_APP_LOCATION_SUCCESS";

// upload address image
export const TOPOMGMTFLOATTAB_UPLOAD_IMAGE_REQUEST = "TOPOMGMTFLOATTAB/APPLICATION_UPLOAD_IMAGE_REQUEST";
export const TOPOMGMTFLOATTAB_UPLOAD_IMAGE_SUCCESS = "TOPOMGMTFLOATTAB/APPLICATION_UPLOAD_IMAGE_SUCCESS";
export const TOPOMGMTFLOATTAB_UPLOAD_IMAGE_FAILURE = "TOPOMGMTFLOATTAB/APPLICATION_UPLOAD_IMAGE_FAILURE";

export const TOPOMGMTFLOATTAB_SEND_DEVICE_COMMAND = "TOPOMGMTFLOATTAB/SEND_DEVICE_COMMAND";
