// export const PASS_TEXT_TO_COMPB = "DEMO/PASS_TEXT_TO_COMPB";

export const COUNT_DEVICE_REQUEST = "USAGE/DEVICE/COUNT_DEVICE_REQUEST";
export const COUNT_DEVICE_REQUEST_SUCCESS = "COUNT/DEVICE/REQUEST/SUCCESS";
export const GET_DEVICE_DATA_FROM_API = "USAGE/DEVICE/GET_DEVICE_DATA_FROM_API";
export const GET_DEVICE_DATA_FROM_API_SUCCESS = "USAGE/DEVICE/GET_DEVICE_DATA_FROM_API_SUCCESS";
export const GET_ONE_WEEK_DEVICE_DATA_FROM_API = "USAGE/DEVICE/GET_ONE_WEEK_DEVICE_DATA_FROM_API";
export const GET_ONE_WEEK_DEVICE_DATA_FROM_API_SUCCESS = "USAGE/DEVICE/GET_ONE_WEEK_DEVICE_DATA_FROM_API_SUCCESS";
export const GET_ONE_MONTH_DEVICE_DATA_FROM_API = "USAGE/DEVICE/GET_ONE_MONTH_DEVICE_DATA_FROM_API";
export const GET_ONE_MONTH_DEVICE_DATA_FROM_API_SUCCESS = "USAGE/DEVICE/GET_ONE_MONTH_DEVICE_DATA_FROM_API_SUCCESS";
export const GET_SIX_MONTHS_DEVICE_DATA_FROM_API = "USAGE/DEVICE/GET_SIX_MONTHS_DEVICE_DATA_FROM_API";
export const GET_SIX_MONTHS_DEVICE_DATA_FROM_API_SUCCESS = "USAGE/DEVICE/GET_SIX_MONTHS_DEVICE_DATA_FROM_API_SUCCESS";
export const GET_ONE_YEAR_DEVICE_DATA_FROM_API = "USAGE/DEVICE/GET_ONE_YEAR_DEVICE_DATA_FROM_API";
export const GET_ONE_YEAR_DEVICE_DATA_FROM_API_SUCCESS = "USAGE/DEVICE/GET_ONE_YEAR_DEVICE_DATA_FROM_API_SUCCESS";






