/*
 * =========================================================================
 *  Copyright (C)2018 NCS Pte. Ltd. All Rights Reserved
 *
 *  This software is confidential and proprietary to NCS Pte. Ltd. You shall
 *  use this software only in accordance with the terms of the license
 *  agreement you entered into with NCS.  No aspect or part or all of this
 *  software may be reproduced, modified or disclosed without full and
 *  direct written authorisation from NCS.
 *
 *  NCS SUPPLIES THIS SOFTWARE ON AN "AS IS" BASIS. NCS MAKES NO
 *  REPRESENTATIONS OR WARRANTIES, EITHER EXPRESSLY OR IMPLIEDLY, ABOUT THE
 *  SUITABILITY OR NON-INFRINGEMENT OF THE SOFTWARE. NCS SHALL NOT BE LIABLE
 *  FOR ANY LOSSES OR DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
 *  MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 *  =========================================================================
 */
/**
 * Created by SongCheng on 20/05/2018.
 */
export const ALARM_INITDATA_REQUEST_SUCCESS = "ALARM/INITDATA_REQUEST_SUCCESS";
export const ALARM_REQUEST_FAILED = "ALARM/REQUEST_FAILED";

export const ALARM_DRAWER_TOGGLE = "ALARM/DRAWER_TOGGLE";
export const ALARM_GETDETAIL_REQUEST = "ALARM/GETDETAIL_REQUEST";
export const ALARM_GETDETAIL_REQUEST_SUCCESS = "ALARM/GETDETAIL_REQUEST_SUCCESS";

export const ALARM_ITEMSDATA_SAVE = "ALARM/ITEMSDATA_SAVE";
export const ALARM_SELECTCOLUMNS_SAVE = "ALARM/SELECTCOLUMNS_SAVE";
export const ALARM_SEARCHTIME_SAVE = "ALARM/SEARCHTIME_SAVE";

export const ALARM_REQUEST_ITEMSSEARCH = "ALARM/REQUEST_ITEMSSEARCH";
export const ALARM_GETDETAILMEDIA_REQUEST = "ALARM/GETDETAILMEDIA_REQUEST";
export const ALARM_GETDETAILMEDIA_REQUEST_SUCCESS = "ALARM/GETDETAILMEDIA_REQUEST_SUCCESS";

export const ALARM_CCMS_ACTION = "ALARM/CCMS_ACTION";

export const ALARM_EDITOR_CONTROL_PROPS = "ALARM/EDITOR_CONTROL_PROPS";

export const ALARM_SORTERDATA_SAVE = "ALARM/SORTERDATA_SAVE";

export const ALARM_CHANGE_DISPLAY_TYPE = "ALARM/CHANGE_DISPLAY_TYPE";

//for Refresh
export const RECEIVE_WEBSOCKET_MESSAGE = "ISC/RECIEVED_MESSAGE";
export const REFRESH_ACTION = "ISC/REFRESH_ACTION";

//for export
export const EXPORT_ALARM_DATA_REQUEST = "ALARM/EXPORT_ALARM_DATA_REQUEST";
export const EXPORT_ALARM_DATA_SUCCESS = "ALARM/EXPORT_ALARM_DATA_SUCCESS";
export const EXPORT_EVENT_ALARM_DATA_FAILURE = "ALARM/EXPORT_EVENT_ALARM_DATA_FAILURE";
export const EXPORT_ALARM_DETAIL_REQUEST = "ALARM/EXPORT_ALARM_DETAIL_REQUEST";

//save pageLimit
export const ALARM_SAVE_ROWSPERPAGE = "ALARM/SAVE_ROWSPERPAGE";

//save streaming data
export const ALARM_SAVE_STREAMING_DATA = "ALARM/SAVE_STREAMING_DATA";

//get stream data
export const ALARM_STREAM_REQUEST = "ALARM/STREAM_REQUEST";
export const ALARM_STREAM_REQUEST_SUCCESS = "ALARM/STREAM_REQUEST_SUCCESS";

//save sort result
export const ALARM_SAVE_SORTRESULT = "EVENT/SAVE_SORTRESULT";

//get parameter name
export const ALARM_PARAMETERS_REQUEST = "ALARM/PARAMETERS_REQUEST";
export const ALARM_PARAMETERS_REQUEST_SUCCESS = "ALARM/PARAMETERS_REQUEST_SUCCESS";

//change alarm state
export const ALARM_CHANGE_STATE_REQUEST = "ALARM/CHANGE_STATE_REQUEST";
export const ALARM_CHANGE_STATE_REQUEST_SUCCESS = "ALARM/CHANGE_STATE_REQUEST_SUCCESS";

//get associations data
export const ALARM_GET_ASSOCIATIONS_DATA = "ALARM/GET_ASSOCIATIONS_DATA";
export const ALARM_GET_ASSOCIATIONS_DATA_SUCCESS = "ALARM/GET_ASSOCIATIONS_DATA_SUCCESS";
export const ALARM_RESET_ASSOCIATIONS_DATA = "ALARM/RESET_ASSOCIATIONS_DATA";

//associate item
export const ALARM_ASSOCIATE_ITEM = "ALARM/ASSOCIATE_ITEM";

//dissociate item
export const ALARM_DISSOCIATE_ITEM = "ALARM/DISSOCIATE_ITEM";
export const ALARM_DISSOCIATE_ITEM_SUCCESS = "ALARM/DISSOCIATE_ITEM_SUCCESS";
export const ALARM_UPDATE_LISTDETAIL = "ALARM/UPDATE_LISTDETAIL";
export const ALARM_UPDATE_LISTDETAIL_SUCCESS = "ALARM/UPDATE_LISTDETAIL_SUCCESS";

//ALARM_ASSOCIATION_SEARCH_REQUEST
export const ALARM_ASSOCIATION_SEARCH_REQUEST = "ALARM/ASSOCIATION_SEARCH_REQUEST";
export const ALARM_ASSOCIATION_SEARCH_REQUEST_SUCCESS = "ALARM/ASSOCIATION_SEARCH_REQUEST_SUCCESS";

//ALARM_POST_EDIT_DATA
export const ALARM_POST_EDIT_DATA = "ALARM/POST_EDIT_DATA";
export const ALARM_POST_EDIT_DATA_SUCCESS = "ALARM/POST_EDIT_DATA_SUCCESS";

//ALARM_GET_USER_LIST
export const ALARM_GET_USER_LIST = "ALARM/GET_USER_LIST";
export const ALARM_GET_USER_LIST_SUCCESS = "ALARM/GET_USER_LIST_SUCCESS";

//ALARM_GET_COMMENTS_DATA
export const ALARM_GET_COMMENTS_DATA = "ALARM/COMMENTS_DATA";
export const ALARM_GET_COMMENTS_DATA_SUCCESS = "ALARM/COMMENTS_DATA_SUCCESS";

//ALARM_POST_COMMENTS
export const ALARM_POST_COMMENTS = "ALARM/POST_COMMENTS";
export const ALARM_POST_FILE_ID = "ALARM/POST_FILE_ID";

//ALARM_UPLOAD_FILE
export const ALARM_UPLOAD_FILE = "ALARM/UPLOAD_FILE";
export const ALARM_UPLOAD_FILE_SUCCESS = "ALARM/UPLOAD_FILE_SUCCESS";

//ALARM_CLOSE_WS_LOCK
export const ALARM_CLOSE_WS_LOCK = "ALARM/CLOSE_WS_LOCK";

//ALARM_GET_PAGE_KEY
export const ALARM_GET_PAGE_KEY = "ALARM/GET_PAGE_KEY";
export const ALARM_GET_PAGE_KEY_SUCCESS = "ALARM/GET_PAGE_KEY_SUCCESS";
