export const LOGGER_DOWNLOAD_FILE = "LOGGER/DOWNLOAD_FILE";

export const LOGGER_DOWNLOAD_FILE_SUCCESS = "LOGGER/DOWNLOAD_FILE_SUCCESS";

export const LOGGER_GET_LOG_LIST_REQUEST = "LOGGER/GET_LOG_LIST_REQUEST";

export const LOGGER_GET_MODULES_REQUEST = "LOGGER/GET_MODULES";

export const LOGGER_GET_MODULES_CHILD_REQUEST = "LOGGER/GET_MODULES_CHILD";

export const LOGGER_GET_LOG_LIST_REQUEST_SUCCESS = "LOGGER/GET_LOG_LIST_REQUEST_SUCCESS";

export const LOGGER_GET_MODULES_REQUEST_SUCCESS = "LOGGER/GET_MODULES_REQUEST_SUCCESS";

export const LOGGER_GET_MODULES_CHILD_REQUEST_SUCCESS = "LOGGER/GET_MODULES_REQUEST_CHILD_SUCCESS";

export const LOGGER_CHANGE_LOADING = "LOGGER/CHANGE_LOADING";

export const LOGGER_RESET = "LOGGER_RESET";

//for Refresh
export const RECEIVE_WEBSOCKET_MESSAGE = "ISC/RECIEVED_MESSAGE";
export const REFRESH_ACTION = "ISC/REFRESH_ACTION";
export const AUTO_REFRESH_INIT = "ISC/AUTO_REFRESH_INIT";
export const PUBLISH_MESSAGE = "ISC/PUBLISH_MESSAGE";
