export const SOP_INIT_DATA = "ISC/SOP_INIT_DATA";
export const SOP_LIST_QRQUEST = "ISC/SOP_LIST_QRQUEST";
export const SOP_LIST_QRQUEST_SUCCESS = "ISC/SOP_LIST_QRQUEST_SUCCESS";
export const SOP_LIST_SEARCH_CHANGE = "ISC/SOP_LIST_SEARCH_CHANGE";
export const SOP_LIST_PAGINATIONCHANGE_CHANGE = "ISC/SOP_LIST_PAGINATIONCHANGE_CHANGE";
export const SOP_LIST_SELECT_SOP = "ISC/SOP_LIST_SELECT_SOP";
export const SOP_ADD_NEW_SOPS = "ISC/SOP_ADD_NEW_SOPS";
export const SOP_EDIT_SOPS = "ISC/SOP_EDIT_SOPS";
export const SOP_ADD_NEW_FLOW_FILE = "ISC/SOP_ADD_NEW_FLOW_FILE";
export const SOP_ADD_CHANGE = "ISC/SOP_ADD_CHANGE";
export const SOP_LIST_DELET = "ISC/SOP_LIST_DELET";
export const SOP_COLUMN_LIST = "ISC/SOP_COLUMN_LIST";
export const SOP_EDITOR_CONTROL_PROPS = "ISC/SOP_EDITOR_CONTROL_PROPS";
export const SOP_CHANGE_SOPS_LIST = "ISC/SOP_CHANGE_SOPS_LIST";
export const SOP_MESSAGE = "ISC/SOP_MESSAGE";
export const SOP_GET_SOP_MANAGMENT_SCHEMA = "ISC/SOP_GET_SOP_MANAGMENT_SCHEMA";
export const SOP_GET_SOP_MANAGMENT_SCHEMA_SUCCESS = "ISC/SOP_GET_SOP_MANAGMENT_SCHEMA_SUCCESS";


