export const SECURITY_ACTIVITION_USER_REQUEST = "SECURITY/ACTIVITION_USER_REQUEST";
export const SECURITY_ACTIVITION_RESET = "SECURITY/ACTIVITION_RESET";
export const SECURITY_ACTIVITION_ISVAILTOEKN = "SECURITY/ACTIVITION_ISVAILTOEKN";
