/*
* =========================================================================
*  Copyright (C)2018 NCS Pte. Ltd. All Rights Reserved
*
*  This software is confidential and proprietary to NCS Pte. Ltd. You shall
*  use this software only in accordance with the terms of the license
*  agreement you entered into with NCS.  No aspect or part or all of this
*  software may be reproduced, modified or disclosed without full and
*  direct written authorisation from NCS.
*
*  NCS SUPPLIES THIS SOFTWARE ON AN "AS IS" BASIS. NCS MAKES NO
*  REPRESENTATIONS OR WARRANTIES, EITHER EXPRESSLY OR IMPLIEDLY, ABOUT THE
*  SUITABILITY OR NON-INFRINGEMENT OF THE SOFTWARE. NCS SHALL NOT BE LIABLE
*  FOR ANY LOSSES OR DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
*  MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*
*  =========================================================================
*/
/**
 * Created by xulu on 25/05/2018.
 */
export const TOPOLOGY_INIT_PROPS = "TOPOLOGYSTATUS/INIT_PROPS";
export const TOPOLOGY_REQUEST = "TOPOLOGYSTATUS/REQUEST";
export const TOPOLOGY_REQUEST_SUCCESS = "TOPOLOGYSTATUS/REQUEST_SUCCESS";

export const TOPOLOGY_FLOATTAB_OPEN = "TOPOLOGYSTATUS/FLOATTAB_OPEN";
export const TOPOLOGY_FLOATTAB_CLOSE = "TOPOLOGYSTATUS/FLOATTAB_CLOSE";
export const TOPOLOGY_FLOATTAB_TOGGLE = "TOPOLOGYSTATUS/FLOATTAB_TOGGLE";

export const TOPOLOGY_COLUMN_FILTER_CHANGE = "TOPOLOGYSTATUS/COLUMN_FILTER_CHANGE";

export const TOPOLOGY_CCMS_CONTROL = "TOPOLOGYSTATUS/CCMS_CONTROL";

export const TOPOLOGY_EDITOR_CONTROL_PROPS = "TOPOLOGYSTATUS/EDITOR_CONTROL_PROPS";

export const TOPOLOGY_STORE_COLUMN_FILTER = "TOPOLOGYSTATUS/STORE_COLUMN_FILTER";

export const TOPOLOGY_MULTIPLE_SELECT = "TOPOLOGYSTATUS/MULTIPLE_SELECT";

export const TOPOLOGY_SORT_CHANGED = "TOPOLOGYSTATUS/SORT_CHANGED";

export const TOPOLOGY_EXPORT_TOPOLOGY_DATA = "TOPOLOGYSTATUS/EXPORT_TOPOLOGY_DATA";

export const TOPOLOGY_EXPORT_TOPOLOGY_DATA_SUCCESS = "TOPOLOGYSTATUS/EXPORT_TOPOLOGY_DATA_SUCCESS";
export const TOPOLOGY_CHANGE_DISPLAY_TYPE = "TOPOLOGYSTATUS/CHANGE_DISPLAY_TYPE";

export const TOPOLOGY_GET_SYSCONFIG_DEVICE_TYPE = "TOPOLOGYSTATUS/GET_SYSCONFIG_DEVICE_TYPE";
export const TOPOLOGY_GET_SYSCONFIG_DEVICE_TYPE_SUCCESS = "TOPOLOGYSTATUS/GET_SYSCONFIG_DEVICE_TYPE_SUCCESS";

export const TOPOLOGY_GET_SYSCONFIG_DEVICE_SCHEMA = "TOPOLOGYSTATUS/GET_SYSCONFIG_DEVICE_SCHEMA";
export const TOPOLOGY_GET_SYSCONFIG_DEVICE_SCHEMA_SUCCESS = "TOPOLOGYSTATUS/GET_SYSCONFIG_DEVICE_SCHEMA_SUCCESS";

export const TOPOLOGY_GET_SYSCONFIG_DEVICE_TYPE_SCHEMA = "TOPOLOGYSTATUS/GET_SYSCONFIG_DEVICE_TYPE_SCHEMA";
export const TOPOLOGY_GET_SYSCONFIG_DEVICE_TYPE_SCHEMA_SUCCESS = "TOPOLOGYSTATUS/GET_SYSCONFIG_DEVICE_TYPE_SCHEMA_SUCCESS";

//refresh
export const RECEIVE_WEBSOCKET_MESSAGE = "ISC/RECIEVED_MESSAGE";
export const SUBSCRIBE_MESSAGE = "ISC/SUBSCRIBE_MESSAGE";
export const AUTO_REFRESH_ACTION = "ISC/REFRESH_ACTION";
export const AUTO_REFRESH_INIT = "ISC/AUTO_REFRESH_INIT";
