// export const PASS_TEXT_TO_COMPB = "DEMO/PASS_TEXT_TO_COMPB";

// export const GET_EVENTS_DATA_FROM_API = "USAGE/EMAIL/GET_EVENTS_DATA_FROM_API";
// export const GET_EVENTS_DATA_FROM_API_SUCCESS = "USAGE/EMAIL/GET_EVENTS_DATA_FROM_API_SUCCESS";

export const GET_EMAIL_DATA_FROM_API = "USAGE/EMAIL/GET_EMAIL_DATA_FROM_API";
export const GET_ONE_WEEK_EMAIL_DATA_FROM_API = "USAGE/EMAIL/GET_ONE_WEEK_EMAIL_DATA_FROM_API";
export const GET_ONE_MONTH_EMAIL_DATA_FROM_API = "USAGE/EMAIL/GET_ONE_MONTH_EMAIL_DATA_FROM_API";
export const GET_SIX_MONTHS_EMAIL_DATA_FROM_API = "USAGE/EMAIL/GET_SIX_MONTHS_EMAIL_DATA_FROM_API";
export const GET_ONE_YEAR_EMAIL_DATA_FROM_API = "USAGE/EMAIL/GET_ONE_YEAR_EMAIL_DATA_FROM_API";

export const GET_EMAIL_DATA_FROM_API_SUCCESS = "USAGE/EMAIL/GET_EMAIL_DATA_FROM_API_SUCCESS";
export const GET_ONE_WEEK_EMAIL_DATA_FROM_API_SUCCESS = "USAGE/EMAIL/GET_ONE_WEEK_EMAIL_DATA_FROM_API_SUCCESS";
export const GET_ONE_MONTH_EMAIL_DATA_FROM_API_SUCCESS = "USAGE/EMAIL/GET_ONE_MONTH_EMAIL_DATA_FROM_API_SUCCESS";
export const GET_SIX_MONTHS_EMAIL_DATA_FROM_API_SUCCESS = "USAGE/EMAIL/GET_SIX_MONTHS_EMAIL_DATA_FROM_API_SUCCESS";
export const GET_ONE_YEAR_EMAIL_DATA_FROM_API_SUCCESS = "USAGE/EMAIL/GET_ONE_YEAR_EMAIL_DATA_FROM_API_SUCCESS";



