/*
* =========================================================================
*  Copyright (C)2018 NCS Pte. Ltd. All Rights Reserved
*
*  This software is confidential and proprietary to NCS Pte. Ltd. You shall
*  use this software only in accordance with the terms of the license
*  agreement you entered into with NCS.  No aspect or part or all of this
*  software may be reproduced, modified or disclosed without full and
*  direct written authorisation from NCS.
*
*  NCS SUPPLIES THIS SOFTWARE ON AN "AS IS" BASIS. NCS MAKES NO
*  REPRESENTATIONS OR WARRANTIES, EITHER EXPRESSLY OR IMPLIEDLY, ABOUT THE
*  SUITABILITY OR NON-INFRINGEMENT OF THE SOFTWARE. NCS SHALL NOT BE LIABLE
*  FOR ANY LOSSES OR DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
*  MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*
*  =========================================================================
*/
/**
 * Created by xulu on 25/05/2018.
 */
export const TOPOLOGYMGMT_INIT_PROPS = "TOPOLOGYMGMT/INIT_PROPS";
export const TOPOLOGYMGMT_INIT_ALL_REDUX = "TOPOLOGYMGMT/INIT_ALL_REDUX ";

export const TOPOLOGYMGMT_REQUEST = "TOPOLOGYMGMT/REQUEST";
export const TOPOLOGYMGMT_REQUEST_SUCCESS = "TOPOLOGYMGMT/REQUEST_SUCCESS";
export const TOPOLOGYMGMT_TYPE_REQUEST = "TOPOLOGYMGMT/TYPE_REQUEST";
export const TOPOLOGYMGMT_TYPE_REQUEST_SUCCESS = "TOPOLOGYMGMT/TYPE_REQUEST_SUCCESS";

export const TOPOLOGYMGMT_FLOATTAB_OPEN = "TOPOLOGYMGMT/FLOATTAB_OPEN";
export const TOPOLOGYMGMT_FLOATTAB_CLOSE = "TOPOLOGYMGMT/FLOATTAB_CLOSE";

export const TOPOLOGYMGMT_COLUMN_FILTER_CHANGE = "TOPOLOGYMGMT/COLUMN_FILTER_CHANGE";

export const TOPOLOGYMGMT_STORE_COLUMN_FILTER = "TOPOLOGYMGMT/STORE_COLUMN_FILTER";

export const TOPOLOGYMGMT_MULTIPLE_SELECT = "TOPOLOGYMGMT/MULTIPLE_SELECT";

export const TOPOLOGYMGMT_SORT_CHANGED = "TOPOLOGYMGMT/SORT_CHANGED";

export const TOPOLOGYMGMT_CHANGETAB = "TOPOLOGYMGMT/CHANGETAB";

export const TOPOLOGYMGMT_DELETE_DEVICE = "TOPOLOGYMGMT/DELETE_DEVICE";
export const TOPOLOGYMGMT_DELETE_DEVICE_SUCCESS = "TOPOLOGYMGMT/DELETE_DEVICE_SUCCESS";

export const TOPOLOGYMGMT_DELETE_DEVICE_TYPE = "TOPOLOGYMGMT/DELETE_DEVICE_TYPE";
export const TOPOLOGYMGMT_DELETE_DEVICE_TYPE_SUCCESS = "TOPOLOGYMGMT/DELETE_DEVICE_TYPE_SUCCESS";

export const TOPOLOGYMGMT_REFRESH = "TOPOLOGYMGMT/REFRESH";

// delete sysconfig device type
export const TOPOLOGYMGMT_DELETE_SYSCONFIG_DEVICE_TYPE = "TOPOLOGYMGMT/DELETE_SYSCONFIG_DEVICE_TYPE";

// get sysconfig all device type
export const TOPOLOGYMGMT_GET_SYSCONFIG_DEVICE_TYPE = "TOPOLOGYMGMT/GET_SYSCONFIG_DEVICE_TYPE";
export const TOPOLOGYMGMT_GET_SYSCONFIG_DEVICE_TYPE_SUCCESS = "TOPOLOGYMGMT/GET_SYSCONFIG_DEVICE_TYPE_SUCCESS";

// get sysconfig basic types
export const TOPOLOGYMGMT_GET_SYSCONFIG_BASIC_TYPE = "TOPOLOGYMGMT/GET_SYSCONFIG_BASIC_TYPE";
export const TOPOLOGYMGMT_GET_SYSCONFIG_BASIC_TYPE_SUCCESS = "TOPOLOGYMGMT/GET_SYSCONFIG_BASIC_TYPE_SUCCESS";

// get sysconfig device schema
export const TOPOLOGYMGMT_GET_SYSCONFIG_DEVICE_SCHEMA = "TOPOLOGYMGMT/GET_SYSCONFIG_DEVICE_SCHEMA";
export const TOPOLOGYMGMT_GET_SYSCONFIG_DEVICE_SCHEMA_SUCCESS = "TOPOLOGYMGMT/GET_SYSCONFIG_DEVICE_SCHEMA_SUCCESS";

// get sysconfig device type schema
export const TOPOLOGYMGMT_GET_SYSCONFIG_DEVICE_TYPE_SCHEMA = "TOPOLOGYMGMT/GET_SYSCONFIG_DEVICE_TYPE_SCHEMA";
export const TOPOLOGYMGMT_GET_SYSCONFIG_DEVICE_TYPE_SCHEMA_SUCCESS = "TOPOLOGYMGMT/GET_SYSCONFIG_DEVICE_TYPE_SCHEMA_SUCCESS";

// get sysconfig integration systems
export const TOPOLOGYMGMT_GET_SYSCONFIG_INTEGRATION_SYSTEM = "TOPOLOGYMGMT/GET_SYSCONFIG_INTEGRATION_SYSTEM";
export const TOPOLOGYMGMT_GET_SYSCONFIG_INTEGRATION_SYSTEM_SUCCESS = "TOPOLOGYMGMT/GET_SYSCONFIG_INTEGRATION_SYSTEM_SUCCESS";

//refresh
export const RECEIVE_WEBSOCKET_MESSAGE = "ISC/RECIEVED_MESSAGE";
export const SUBSCRIBE_MESSAGE = "ISC/SUBSCRIBE_MESSAGE";
export const AUTO_REFRESH_ACTION = "ISC/REFRESH_ACTION";
export const AUTO_REFRESH_INIT = "ISC/AUTO_REFRESH_INIT";
