
export const TASK_CHECK = "ISC/TASK_CHECK";
export const TASK_SEARCH_TEXT_CHANGE = "ISC/TASK_SEARCH_TEXT_CHANGE";
export const TASK_SEARCH_TEXT_CHANGE_SUCCESS = "ISC/TASK_SEARCH_TEXT_CHANGE_SUCCESS";
