// export const PASS_TEXT_TO_COMPB = "DEMO/PASS_TEXT_TO_COMPB";

// export const GET_EVENTS_DATA_FROM_API = "USAGE/EVENTS/GET_EVENTS_DATA_FROM_API";
// export const GET_EVENTS_DATA_FROM_API_SUCCESS = "USAGE/EVENTS/GET_EVENTS_DATA_FROM_API_SUCCESS";

export const GET_EVENT_DATA_FROM_API = "USAGE/EVENTS/GET_EVENT_DATA_FROM_API";
export const GET_ONE_WEEK_EVENT_DATA_FROM_API = "USAGE/EVENTS/GET_ONE_WEEK_EVENT_DATA_FROM_API";
export const GET_ONE_MONTH_EVENT_DATA_FROM_API = "USAGE/EVENTS/GET_ONE_MONTH_EVENT_DATA_FROM_API";
export const GET_SIX_MONTHS_EVENT_DATA_FROM_API = "USAGE/EVENTS/GET_SIX_MONTHS_EVENT_DATA_FROM_API";
export const GET_ONE_YEAR_EVENT_DATA_FROM_API = "USAGE/EVENTS/GET_ONE_YEAR_EVENT_DATA_FROM_API";

export const GET_EVENT_DATA_FROM_API_SUCCESS = "USAGE/EVENTS/GET_EVENT_DATA_FROM_API_SUCCESS";
export const GET_ONE_WEEK_EVENT_DATA_FROM_API_SUCCESS = "USAGE/EVENTS/GET_ONE_WEEK_EVENT_DATA_FROM_API_SUCCESS";
export const GET_ONE_MONTH_EVENT_DATA_FROM_API_SUCCESS = "USAGE/EVENTS/GET_ONE_MONTH_EVENT_DATA_FROM_API_SUCCESS";
export const GET_SIX_MONTHS_EVENT_DATA_FROM_API_SUCCESS = "USAGE/EVENTS/GET_SIX_MONTHS_EVENT_DATA_FROM_API_SUCCESS";
export const GET_ONE_YEAR_EVENT_DATA_FROM_API_SUCCESS = "USAGE/EVENTS/GET_ONE_YEAR_EVENT_DATA_FROM_API_SUCCESS";



