export const LOGIN_REQUEST = "ISC/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "ISC/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "ISC/LOGIN_FAILURE";

export const IS_TOKEN_VALID_REQUEST = "ISC/IS_TOKEN_VALID_REQUEST";
// export const IS_TOKEN_VALID_SUCCESS = "ISC/IS_TOKEN_VALID_SUCCESS";
// export const IS_TOKEN_VALID_FAILURE = "ISC/IS_TOKEN_VALID_FAILURE";

export const LOGOUT_REQUEST = "ISC/LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "ISC/LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "ISC/LOGOUT_FAILURE";

export const KEEP_ALIVE_REQUEST = "ISC/KEEP_ALIVE_REQUEST";
// export const KEEP_ALIVE_SUCCESS = "ISC/KEEP_ALIVE_SUCCESS";
// export const KEEP_ALIVE_FAILURE = "ISC/KEEP_ALIVE_FAILURE";

export const CREATE_IDENTIFY = "ISC/CREATE_IDENTIFY";
export const UPDATE_IDENTIFY = "ISC/UPDATE_IDENTIFY";

export const LOGIN_ACCOUNT_REQUEST = "ISC/LOGIN_ACCOUNT_REQUEST";
export const LOGIN_ACCOUNT_SUCCESS = "ISC/LOGIN_ACCOUNT_SUCCESS";
export const LOGIN_CCMS_CONTROL = "LOGIN/CCMS_CONTROL";
export const LOGIN_GROUP = "ISC/LOGIN_GROUP";
export const LOGIN_FORGOT = "ISC/LOGIN_FORGOT";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_REQUEST_SUCCESS = "CHANGE_PASSWORD_REQUEST_SUCCESS";

export const LOGIN_RESET = "LOGIN_RESET";

export const FORGOT_PASSWORD_REQUST = "FORGOT_PASSWORD_REQUST";

export const FORGOT_PASSWORD_GET_SECURITY_CODE_REQUST = "FORGOT_PASSWORD_GET_SECURITY_CODE_REQUST";
export const FORGOT_PASSWORD_VALIDATION_SECURITY_CODE_REQUST = "FORGOT_PASSWORD_VALIDATION_SECURITY_CODE_REQUST";
