export const MESSAGE_INFO = "ISC/MESSAGE_INFO";
export const MESSAGE_WARN = "ISC/MESSAGE_WARN";
export const MESSAGE_ERROR = "ISC/MESSAGE_ERROR";
export const MESSAGE_SUCCESS = "ISC/MESSAGE_SUCCESS";
export const MESSAGE_READ = "ISC/MESSAGE_READ";
export const MESSAGE_CLEAR = "ISC/MESSAGE_CLEAR";
export const MESSAGE_MUTE = "ISC/MESSAGE_MUTE";