export const SAVE_KPI_REQUEST = "KPI/SAVE_KPI_REQUEST";
export const SAVE_KPI_SUCCESS = "KPI/SAVE_KPI_SUCCESS";
export const SAVE_KPI_FAILURE = "KPI/SAVE_KPI_FAILURE";

export const GET_KPI_LIST_REQUEST = "KPI/GET_KPI_LIST_REQUEST";
export const GET_KPI_LIST_SUCCESS = "KPI/GET_KPI_LIST_SUCCESS";
export const GET_KPI_LIST_FAILURE = "KPI/GET_KPI_LIST_FAILURE";

export const KPI_PREVIEW_REQUEST = "KPI/KPI_PREVIEW_REQUEST";
export const KPI_PREVIEW_SUCCESS = "KPI/KPI_PREVIEW_SUCCESS";
export const KPI_PREVIEW_FAILURE = "KPI/KPI_PREVIEW_FAILURE"; 

export const KPI_GET_DBLIST_REQUEST = "KPI/KPI_GET_DBLIST_REQUEST";
export const KPI_GET_DBLIST_SUCCESS = "KPI/KPI_GET_DBLIST_SUCCESS";
export const KPI_GET_DBLIST_FAILURE = "KPI/KPI_GET_DBLIST_FAILURE"; 

export const CHANGE_KPI_PROPERTY = "KPI/CHANGE_KPI_PROPERTY";
export const CHANGE_PROPERTY = "ISC/CHANGE_PROPERTY";