/*
* =========================================================================
*  Copyright (C)2018 NCS Pte. Ltd. All Rights Reserved
*
*  This software is confidential and proprietary to NCS Pte. Ltd. You shall
*  use this software only in accordance with the terms of the license
*  agreement you entered into with NCS.  No aspect or part or all of this
*  software may be reproduced, modified or disclosed without full and
*  direct written authorisation from NCS.
*
*  NCS SUPPLIES THIS SOFTWARE ON AN "AS IS" BASIS. NCS MAKES NO
*  REPRESENTATIONS OR WARRANTIES, EITHER EXPRESSLY OR IMPLIEDLY, ABOUT THE
*  SUITABILITY OR NON-INFRINGEMENT OF THE SOFTWARE. NCS SHALL NOT BE LIABLE
*  FOR ANY LOSSES OR DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
*  MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*
*  =========================================================================
*/
/**
 * Created by Jia Luo on 27/07/2018.
 */
export const SECURITY_GROUP_GET_REQUEST = "SECURITY/GROUP_GET_REQUEST";
export const SECURITY_GROUP_GET_REQUEST_SUCCESS = "SECURITY/GROUP_GET_REQUEST_SUCCESS";
export const SECURITY_GROUP_POST_REQUEST = "SECURITY/GROUP_POST_REQUEST";
export const SECURITY_GROUP_POST_REQUEST_SUCCESS = "SECURITY/GROUP_POST_REQUEST_SUCCESS";
export const SECURITY_GROUP_PUT_REQUEST = "SECURITY/GROUP_PUT_REQUEST";
export const SECURITY_GROUP_PUT_REQUEST_SUCCESS = "SECURITY/GROUP_PUT_REQUEST_SUCCESS";
export const SECURITY_GROUP_DELETE_REQUEST = "SECURITY/GROUP_DELETE_REQUEST";
export const SECURITY_GROUP_DELETE_REQUEST_SUCCESS = "SECURITY/GROUP_DELETE_REQUEST_SUCCESS";

export const SECURITY_GROUP_SELECT = "SECURITY/GROUP_SELECT";

export const SECURITY_LOADING = "SECURITY/LOADING";

export const SECURITY_UPDATE_USER_GROUP = "SECURITY/UPDATE_USER_GROUP";

export const SECURITY_GROUP_RESET = "SECURITY/GROUP_RESET";

export const SECURITY_GROUP_RESET_TEMP = "SECURITY/GROUP_RESET_TEMP";

export const SECURITY_GROUP_VISIABLE = "SECURITY/GROUP_VISIABLE";

export const SECURITY_GROUP_USER_GRPID_REQUEST = "SECURITY/GROUP_USER_GRPID_REQUEST";
export const SECURITY_GROUP_USER_GRPID_SUCCESS = "SECURITY/GROUP_USER_GRPID_SUCCESS";

export const SECURITY_GROUP_APPLICATION_GRPID_REQUEST = "SECURITY/GROUP_APPLICATION_GRPID_REQUEST";
export const SECURITY_GROUP_APPLICATION_GRPID_SUCCESS = "SECURITY/GROUP_APPLICATION_GRPID_SUCCESS";

export const SECURITY_GROUP_FROMID_REQUEST = "SECURITY/GROUP_FROMID_REQUEST";
export const SECURITY_GROUP_FROMID_REQUEST_SUCCESS = "SECURITY/GROUP_FROMID_REQUEST_SUCCESS";

export const SECURITY_GROUP_APPLICATIONS = "SECURITY_GROUP_APPLICATIONS";
