/*
 * @Author: wplei
 * @Date: 2018-11-14 18:53:12
 * @Last Modified by: wplei
 * @Last Modified time: 2018-11-19 13:12:19
 */

export const REQUEST_DASHBOARD_LOADING = "CCMS/REQUEST_DASHBOARD_LOADING";
export const REQUEST_DASHBOARDS = "CCMS/REQUEST_DASHBOARDS";
export const REQUEST_DASHBOARD_SUCCESS = "CCMS/REQUEST_DASHBOARD_SUCCESS";
export const REQUEST_GROUP = "CCMS/REQUEST_GROUP";
export const REQUEST_GROUP_SUCCESS = "CCMS/REQUEST_GROUP_SUCCESS";
export const REQUEST_UPDATE_DASHBOARD_PRIORITY = "CCMS/REQUEST_UPDATE_DASHBOARD_PRIORITY";
export const REQUEST_COUNTS = "CCMS/REQUEST_COUNTS";
export const REQUEST_COUNTS_SUCCESS = "CCMS/REQUEST_COUNTS_SUCCESS";
