
export const TASK_SUBIT_UPLOAD_FILE = "ISC/TASK_SUBIT_UPLOAD_FILE";
export const TASK_CHECK_CURRENT_DATA = "ISC/TASK_CHECK_CURRENT_DATA";
export const TASK_CHECK_CURRENT_DATA_SUCCESS = "ISC/TASK_CHECK_CURRENT_DATA_SUCCESS";
export const TASK_GET_UPLOAD_FILE = "ISC/TASK_GET_UPLOAD_FILE";
export const TASK_GET_FILE_INFO = "ISC/TASK_GET_FILE_INFO";
export const TASK_CHANGE = "ISC/TASK_CHANGE";
export const TASK_GET_FILE_INFO_SUCCESS = "ISC/TASK_GET_FILE_INFO_SUCCESS";
export const TASK_REMOVE_FILE = "ISC/TASK_REMOVE_FILE";
export const TASK_REMOVE_IS_LOADING = "ISC/TASK_REMOVE_IS_LOADING";
export const TASK_GET__FILE_BY_TASKID = "ISC/TASK_GET__FILE_BY_TASKID";
export const TASK_GET__FILE_BY_TASKID_SUCCESS = "ISC/TASK_GET__FILE_BY_TASKID_SUCCESS";
export const TASK_GET__FILE_BY_UPADE_SUCCESS = "ISC/TASK_GET__FILE_BY_UPADE_SUCCESS";

