export const SECURITY_FORGOT_PASSWORD_USER_REQUEST = "SECURITY/FORGOT_PASSWORD_USER_REQUEST";
export const SECURITY_FORGOT_PASSWORD_RESET = "SECURITY/FORGOT_PASSWORD_RESET";
export const SECURITY_FORGOT_PASSWORD_ISVAILTOEKN = "SECURITY/FORGOT_PASSWORD_ISVAILTOEKN";
