// export const PASS_TEXT_TO_COMPB = "DEMO/PASS_TEXT_TO_COMPB";

// export const GET_EVENTS_DATA_FROM_API = "USAGE/USERS/GET_EVENTS_DATA_FROM_API";
// export const GET_EVENTS_DATA_FROM_API_SUCCESS = "USAGE/USERS/GET_EVENTS_DATA_FROM_API_SUCCESS";

export const GET_USERS_DATA_FROM_API = "USAGE/USERS/GET_USERS_DATA_FROM_API";
export const GET_ONE_WEEK_USERS_DATA_FROM_API = "USAGE/USERS/GET_ONE_WEEK_USERS_DATA_FROM_API";
export const GET_ONE_MONTH_USERS_DATA_FROM_API = "USAGE/USERS/GET_ONE_MONTH_USERS_DATA_FROM_API";
export const GET_SIX_MONTHS_USERS_DATA_FROM_API = "USAGE/USERS/GET_SIX_MONTHS_USERS_DATA_FROM_API";
export const GET_ONE_YEAR_USERS_DATA_FROM_API = "USAGE/USERS/GET_ONE_YEAR_USERS_DATA_FROM_API";

export const GET_USERS_DATA_FROM_API_SUCCESS = "USAGE/USERS/GET_USERS_DATA_FROM_API_SUCCESS";
export const GET_ONE_WEEK_USERS_DATA_FROM_API_SUCCESS = "USAGE/USERS/GET_ONE_WEEK_USERS_DATA_FROM_API_SUCCESS";
export const GET_ONE_MONTH_USERS_DATA_FROM_API_SUCCESS = "USAGE/USERS/GET_ONE_MONTH_USERS_DATA_FROM_API_SUCCESS";
export const GET_SIX_MONTHS_USERS_DATA_FROM_API_SUCCESS = "USAGE/USERS/GET_SIX_MONTHS_USERS_DATA_FROM_API_SUCCESS";
export const GET_ONE_YEAR_USERS_DATA_FROM_API_SUCCESS = "USAGE/USERS/GET_ONE_YEAR_USERS_DATA_FROM_API_SUCCESS";



