export const TASK_LIST = "ISC/TASK_LIST";
export const TASK_SUBMIT = "ISC/TASK_SUBMIT";
export const TASK_CHANGE = "ISC/TASK_CHANGE";
export const TASK_CHECK_CURRENT_DATA = "ISC/TASK_CHECK_CURRENT_DATA";
export const TASK_CHECK_CURRENT_DATA_SUCCESS = "ISC/TASK_CHECK_CURRENT_DATA_SUCCESS";
export const TASK_SUBIT_MESSAGES_INFO = "ISC/TASK_SUBIT_MESSAGES_INFO";
export const TASK_SUBIT_UPLOAD_FILE = "ISC/TASK_SUBIT_UPLOAD_FILE";
export const TASK_GET_UPLOAD_FILE = "ISC/TASK_GET_UPLOAD_FILE";
export const TASK_GET_FILE_INFO = "ISC/TASK_GET_FILE_INFO";
export const TASK_CHECK_CURRENT_XML = "ISC/TASK_CHECK_CURRENT_XML";
export const TASK_CHECK_CURRENT_XML_SUCCESS = "ISC/TASK_CHECK_CURRENT_XML_SUCCESS";
export const TASK_GET_FILE_LIST = "ISC/TASK_GET_FILE_LIST";
export const TASK_GET_FILE = "ISC/TASK_GET_FILE";

export const TASK_GET_FILE_LIST_SUCCESS = "ISC/TASK_GET_FILE_LIST_SUCCESS";