// export const PASS_TEXT_TO_COMPB = "DEMO/PASS_TEXT_TO_COMPB";

// export const GET_EVENTS_DATA_FROM_API = "USAGE/SMS/GET_EVENTS_DATA_FROM_API";
// export const GET_EVENTS_DATA_FROM_API_SUCCESS = "USAGE/SMS/GET_EVENTS_DATA_FROM_API_SUCCESS";

export const GET_SMS_DATA_FROM_API = "USAGE/SMS/GET_SMS_DATA_FROM_API";
export const GET_ONE_WEEK_SMS_DATA_FROM_API = "USAGE/SMS/GET_ONE_WEEK_SMS_DATA_FROM_API";
export const GET_ONE_MONTH_SMS_DATA_FROM_API = "USAGE/SMS/GET_ONE_MONTH_SMS_DATA_FROM_API";
export const GET_SIX_MONTHS_SMS_DATA_FROM_API = "USAGE/SMS/GET_SIX_MONTHS_SMS_DATA_FROM_API";
export const GET_ONE_YEAR_SMS_DATA_FROM_API = "USAGE/SMS/GET_ONE_YEAR_SMS_DATA_FROM_API";

export const GET_SMS_DATA_FROM_API_SUCCESS = "USAGE/SMS/GET_SMS_DATA_FROM_API_SUCCESS";
export const GET_ONE_WEEK_SMS_DATA_FROM_API_SUCCESS = "USAGE/SMS/GET_ONE_WEEK_SMS_DATA_FROM_API_SUCCESS";
export const GET_ONE_MONTH_SMS_DATA_FROM_API_SUCCESS = "USAGE/SMS/GET_ONE_MONTH_SMS_DATA_FROM_API_SUCCESS";
export const GET_SIX_MONTHS_SMS_DATA_FROM_API_SUCCESS = "USAGE/SMS/GET_SIX_MONTHS_SMS_DATA_FROM_API_SUCCESS";
export const GET_ONE_YEAR_SMS_DATA_FROM_API_SUCCESS = "USAGE/SMS/GET_ONE_YEAR_SMS_DATA_FROM_API_SUCCESS";



