/*
* =========================================================================
*  Copyright (C)2018 NCS Pte. Ltd. All Rights Reserved
*
*  This software is confidential and proprietary to NCS Pte. Ltd. You shall
*  use this software only in accordance with the terms of the license
*  agreement you entered into with NCS.  No aspect or part or all of this
*  software may be reproduced, modified or disclosed without full and
*  direct written authorisation from NCS.
*
*  NCS SUPPLIES THIS SOFTWARE ON AN "AS IS" BASIS. NCS MAKES NO
*  REPRESENTATIONS OR WARRANTIES, EITHER EXPRESSLY OR IMPLIEDLY, ABOUT THE
*  SUITABILITY OR NON-INFRINGEMENT OF THE SOFTWARE. NCS SHALL NOT BE LIABLE
*  FOR ANY LOSSES OR DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
*  MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*
*  =========================================================================
*/
/**
* Created by KaiDi on 25/05/2018.
*/
export const CHANGE_USE_STATE = "CHART/CHANGE_USE_STATE";
// export const DESTROY_DATA = "CHART/DESTROY_DATA";

export const TOPOLOGY_REQUEST = "CHART/TOPOLOGY_REQUEST";
export const TOPOLOGY_SUCCESS = "CHART/TOPOLOGY_SUCCESS";
export const TOPOLOGY_FAILURE = "CHART/TOPOLOGY_FAILURE";

export const DEVICEMODEL_PROPERTY_REQUEST = "CHART/DEVICEMODEL_PROPERTY_REQUEST";
export const DEVICEMODEL_PROPERTY_SUCCESS = "CHART/DEVICEMODEL_PROPERTY_SUCCESS";
export const DEVICEMODEL_PROPERTY_FAILURE = "CHART/DEVICEMODEL_PROPERTY_FAILURE";

export const TOPOLOGY_STATIC_REQUEST = "CHART/TOPOLOGY_STATIC_REQUEST";
export const TOPOLOGY_STATIC_SUCCESS = "CHART/TOPOLOGY_STATIC_SUCCESS";
export const TOPOLOGY_STATIC_FAILURE = "CHART/TOPOLOGY_STATIC_FAILURE";

export const ALARM_REQUEST = "CHART/ALARM_REQUEST";
export const ALARM_SUCCESS = "CHART/ALARM_SUCCESS";
export const ALARM_FAILURE = "CHART/ALARM_FAILURE";

export const EVENT_REQUEST = "CHART/EVENT_REQUEST";
export const EVENT_SUCCESS = "CHART/EVENT_SUCCESS";
export const EVENT_FAILURE = "CHART/EVENT_FAILURE";

export const KPI_PREVIEW_REQUEST = "CHART/KPI_PREVIEW_REQUEST";
export const KPI_PREVIEW_SUCCESS = "CHART/KPI_PREVIEW_SUCCESS";
export const KPI_PREVIEW_FAILURE = "CHART/KPI_PREVIEW_FAILURE";

export const KPI_SERVICE_REQUEST = "CHART/KPI_SERVICE_REQUEST";
export const KPI_SERVICE_SUCCESS = "CHART/KPI_SERVICE_SUCCESS";
export const KPI_SERVICE_FAILURE = "CHART/KPI_SERVICE_FAILURE";

export const GET_KPI_LIST_REQUEST = "CHART/GET_KPI_LIST_REQUEST";
export const GET_KPI_LIST_SUCCESS = "CHART/GET_KPI_LIST_SUCCESS";
export const GET_KPI_LIST_FAILURE = "CHART/GET_KPI_LIST_FAILURE";

//for query builder
export const CHANGE_PROPERTY = "CHART/CHANGE_PROPERTY";
export const APPLY_DEFAULT_PROPERTY = "CHART/APPLY_DEFAULT_PROPERTY";


//for export 
export const EXPORT_EVENT_ALARM_DATA_REQUEST = "CHART/EXPORT_EVENT_ALARM_DATA_REQUEST";
export const EXPORT_EVENT_ALARM_DATA_SUCCESS = "CHART/EXPORT_EVENT_ALARM_DATA_SUCCESS";
export const EXPORT_EVENT_ALARM_DATA_FAILURE = "CHART/EXPORT_EVENT_ALARM_DATA_FAILURE";

//for Refresh
export const RECEIVE_WEBSOCKET_MESSAGE = "ISC/RECIEVED_MESSAGE";
export const REFRESH_ACTION = "ISC/REFRESH_ACTION";
export const AUTO_REFRESH_INIT = "ISC/AUTO_REFRESH_INIT";