/*
* =========================================================================
*  Copyright (C)2018 NCS Pte. Ltd. All Rights Reserved
*
*  This software is confidential and proprietary to NCS Pte. Ltd. You shall
*  use this software only in accordance with the terms of the license
*  agreement you entered into with NCS.  No aspect or part or all of this
*  software may be reproduced, modified or disclosed without full and
*  direct written authorisation from NCS.
*
*  NCS SUPPLIES THIS SOFTWARE ON AN "AS IS" BASIS. NCS MAKES NO
*  REPRESENTATIONS OR WARRANTIES, EITHER EXPRESSLY OR IMPLIEDLY, ABOUT THE
*  SUITABILITY OR NON-INFRINGEMENT OF THE SOFTWARE. NCS SHALL NOT BE LIABLE
*  FOR ANY LOSSES OR DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
*  MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*
*  =========================================================================
*/
/**
 * Created by wangrui on 22/06/2018.
 */
export const RULEFLOATTAB_INIT = "RULEFLOATTAB/INIT";
export const RULEFLOATTAB_SET = "RULEFLOATTAB/SET";
export const RULEFLOATTAB_CHANGETAB = "RULEFLOATTAB/CHANGETAB";

export const RULEFLOATTAB_GETDETAIL = "RULEFLOATTAB/GETDETAIL";
export const RULEFLOATTAB_GETDETAIL_SUCCESS = "RULEFLOATTAB/GETDETAIL_SUCCESS";

export const RULEFLOATTAB_UPDATERULE = "RULEFLOATTAB/UPDATERULE";
export const RULEFLOATTAB_UPDATERULE_SUCCESS = "RULEFLOATTAB/UPDATERULE_SUCCESS";

export const RULEFLOATTAB_ADDRULE = "RULEFLOATTAB/ADDRULE";
export const RULEFLOATTAB_ADDRULE_SUCCESS = "RULEFLOATTAB/ADDRULE_SUCCESS";

export const RULEFLOATTAB_GET_TOPOLOGY_LIST = "RULEFLOATTAB/GET_TOPOLOGY_LIST";
export const RULEFLOATTAB_GET_TOPOLOGY_LIST_SUCCESS = "RULEFLOATTAB/GET_TOPOLOGY_LIST_SUCCESS";

export const RULEFLOATTAB_GET_DEVICEMODEL_INFO = "RULEFLOATTAB/GET_TOPOLOGY_MODEL";
export const RULEFLOATTAB_GET_DEVICEMODEL_INFO_SUCCESS = "RULEFLOATTAB/GET_TOPOLOGY_MODEL_SUCCESS";
// export const RULE_CHANGE_ADDMODE = "RULE/CHANGE_ADDMODE";
export const RULEFLOATTAB_GET_RULE_CONDITION_CONFIG = "RULEFLOATTAB/GET_RULE_CONDITION_CONFIG";

// export const RULEFLOATTAB_GET_EMAIL_LIST = "RULEFLOATTAB/GET_EMAIL_LIST";
// export const RULEFLOATTAB_GET_EMAIL_LIST_SUCCESS = "RULEFLOATTAB/GET_EMAIL_LIST_SUCCESS";

export const RULEFLOATTAB_UPDATE_NOTIFICATION = "RULEFLOATTAB/UPDATE_NOTIFICATION";

export const RULEFLOATTAB_GET_ACTION_CONTENT = "RULEFLOATTAB/GET_ACTION_CONTENT";
export const RULEFLOATTAB_GET_ACTION_CONTENT_SUCCESS = "RULEFLOATTAB/GET_ACTION_CONTENT_SUCCESS";

export const RULEFLOATTAB_CREATE_NOTIFICATION_CONFIG = "RULEFLOATTAB/CREATE_NOTIFICATION_CONFIG";
export const RULEFLOATTAB_CREATE_WORKFLOW_CONFIG = "RULEFLOATTAB/CREATE_WORKFLOW_CONFIG";

export const RULEFLOATTAB_SAVE_CONFIGS = "RULEFLOATTAB/SAVE_CONFIGS";