/*
* =========================================================================
*  Copyright (C)2018 NCS Pte. Ltd. All Rights Reserved
*
*  This software is confidential and proprietary to NCS Pte. Ltd. You shall
*  use this software only in accordance with the terms of the license
*  agreement you entered into with NCS.  No aspect or part or all of this
*  software may be reproduced, modified or disclosed without full and
*  direct written authorisation from NCS.
*
*  NCS SUPPLIES THIS SOFTWARE ON AN "AS IS" BASIS. NCS MAKES NO
*  REPRESENTATIONS OR WARRANTIES, EITHER EXPRESSLY OR IMPLIEDLY, ABOUT THE
*  SUITABILITY OR NON-INFRINGEMENT OF THE SOFTWARE. NCS SHALL NOT BE LIABLE
*  FOR ANY LOSSES OR DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
*  MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*
*  =========================================================================
*/
/**
 * Created by xulu on 25/05/2018.
 */
export const APPLICATION_INIT_PROPS = "APPLICATION/INIT_PROPS";
export const APPLICATION_INIT= "APPLICATION/INIT";

export const GET_ADDRESS_FROM_LAYER_REQUEST = "APPLICATION/GET_ADDRESS_FROM_LAYER_REQUEST";
export const GET_ADDRESS_FROM_LAYER_SUCCESS = "APPLICATION/GET_ADDRESS_FROM_LAYER_SUCCESS";
export const GET_ADDRESS_FROM_LAYER_FAILURE = "APPLICATION/GET_ADDRESS_FROM_LAYER_FAILURE";

export const APPLICATION_FLOATTAB_OPEN = "APPLICATION/FLOATTAB_OPEN";
export const APPLICATION_FLOATTAB_CLOSE = "APPLICATION/FLOATTAB_CLOSE";
export const APPLICATION_FLOATTAB_TOGGLE = "APPLICATION/FLOATTAB_TOGGLE";

export const DELETE_ADDRESS_REQUEST = "APPLICATION/DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "APPLICATION/DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAILURE = "APPLICATION/DELETE_ADDRESS_FAILURE";

export const APPLICATION_COLUMN_FILTER_CHANGE = "APPLICATION/COLUMN_FILTER_CHANGE";

export const APPLICATION_CCMS_CONTROL = "APPLICATION/CCMS_CONTROL";

export const APPLICATION_EDITOR_CONTROL_PROPS = "APPLICATION/EDITOR_CONTROL_PROPS";

export const APPLICATION_STORE_COLUMN_FILTER = "APPLICATION/STORE_COLUMN_FILTER";

export const APPLICATION_MULTIPLE_SELECT = "APPLICATION/MULTIPLE_SELECT";

export const APPLICATION_SORT_CHANGED = "APPLICATION/SORT_CHANGED";

//refresh
export const RECEIVE_WEBSOCKET_MESSAGE = "ISC/RECIEVED_MESSAGE";
export const SUBSCRIBE_MESSAGE = "ISC/SUBSCRIBE_MESSAGE";
export const AUTO_REFRESH_ACTION = "ISC/REFRESH_ACTION";
export const AUTO_REFRESH_INIT = "ISC/AUTO_REFRESH_INIT";

