/*
* =========================================================================
*  Copyright (C)2018 NCS Pte. Ltd. All Rights Reserved
*
*  This software is confidential and proprietary to NCS Pte. Ltd. You shall
*  use this software only in accordance with the terms of the license
*  agreement you entered into with NCS.  No aspect or part or all of this
*  software may be reproduced, modified or disclosed without full and
*  direct written authorisation from NCS.
*
*  NCS SUPPLIES THIS SOFTWARE ON AN "AS IS" BASIS. NCS MAKES NO
*  REPRESENTATIONS OR WARRANTIES, EITHER EXPRESSLY OR IMPLIEDLY, ABOUT THE
*  SUITABILITY OR NON-INFRINGEMENT OF THE SOFTWARE. NCS SHALL NOT BE LIABLE
*  FOR ANY LOSSES OR DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
*  MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*
*  =========================================================================
*/
/**
 * Created by Jia Luo on 27/07/2018.
 */
export const SECURITY_RESOURCEPATH_GET_REQUEST = "SECURITY/RESOURCEPATH_GET_REQUEST";
export const SECURITY_RESOURCEPATH_GET_REQUEST_SUCCESS = "SECURITY/RESOURCEPATH_GET_REQUEST_SUCCESS";
export const SECURITY_RESOURCEPATH_POST_REQUEST = "SECURITY/RESOURCEPATH_POST_REQUEST";
export const SECURITY_RESOURCEPATH_POST_REQUEST_SUCCESS = "SECURITY/RESOURCEPATH_POST_REQUEST_SUCCESS";
export const SECURITY_RESOURCEPATH_PUT_REQUEST = "SECURITY/RESOURCEPATH_PUT_REQUEST";
export const SECURITY_RESOURCEPATH_PUT_REQUEST_SUCCESS = "SECURITY/RESOURCEPATH_PUT_REQUEST_SUCCESS";
export const SECURITY_RESOURCEPATH_DELETE_REQUEST = "SECURITY/RESOURCEPATH_DELETE_REQUEST";
export const SECURITY_RESOURCEPATH_DELETE_REQUEST_SUCCESS = "SECURITY/RESOURCEPATH_DELETE_REQUEST_SUCCESS";

export const SECURITY_RESOURCEPATH_SELECT = "SECURITY/RESOURCEPATH_SELECT";

export const SECURITY_RESOURCEPATH_RESET = "SECURITY/RESOURCEPATH_RESET";

export const SECURITY_RESOURCEPATH_REQUEST_FAIL = "SECURITY/RESOURCEPATH_REQUEST_FAIL";

export const SECURITY_RESOURCEPATH_RADIO = "SECURITY/RESOURCEPATH_RADIO";

export const SECURITY_RESOURCEPATH_COVER_APPLICATION = "SECURITY/RESOURCEPATH_COVER_APPLICATION";
