export const APPLICATION_DASHBOARD_CONTROL = "APPLICATION/DASHBOARD_CONTROL";
export const APPLICATION_REQUEST = "APPLICATION/REQUEST";
export const APPLICATION_REQUEST_SUCCESS = "APPLICATION/REQUEST_SUCCESS";
export const APPLICATION_LOADING_CONTROL = "APPLICATION/LOADING_CONTROL";
