export const WORKFLOW_REQUEST = "ISC/WORKFLOW_REQUEST";
export const WORKFLOW_UPDATE = "ISC/WORKFLOW_UPDATE";
export const WORKFLOW_TASK_LIST = "ISC/WORKFLOW_TASK_LIST";
export const WORKFLOW_TASK_LIST_SUCCESS = "ISC/WORKFLOW_TASK_LIST_SUCCESS";