// count
export const COUNT_DEVICE_REQUEST = "COUNT_DEVICE_REQUEST";
export const COUNT_EVENTS_REQUEST = "COUNT_EVENTS_REQUEST";
export const COUNT_DEVICE_REQUEST_SUCCESS = "COUNT/DEVICE/REQUEST/SUCCESS";
export const COUNT_EVENTS_REQUEST_SUCCESS = "COUNT/EVENTS/REQUEST/SUCCESS";
export const USAGE_METER_DEVICE_DETAIL = "DEVICE_DATA/REQUEST/SUCCESS";
// export const USAGE_ACCOUNT_LIST_REQUEST = "ACOUNTS_DATA/REQUEST";
export const USAGE_GET_ACOUNTS_DETAIL = "USAGE/USAGE_ACCOUNTS_DETAIL";
export const USAGE_GET_ACCOUNTS_SUCCESS = "USAGE/USAGE_ACCOUNTS_SUCCESS";
export const PASSED_ACCOUNT_ID_TO_OTHER_COMP = "USAGE/PASSED_ACCOUNT_ID_TO_OTHER_COMP";
