/*
* =========================================================================
*  Copyright (C)2018 NCS Pte. Ltd. All Rights Reserved
*
*  This software is confidential and proprietary to NCS Pte. Ltd. You shall
*  use this software only in accordance with the terms of the license
*  agreement you entered into with NCS.  No aspect or part or all of this
*  software may be reproduced, modified or disclosed without full and
*  direct written authorisation from NCS.
*
*  NCS SUPPLIES THIS SOFTWARE ON AN "AS IS" BASIS. NCS MAKES NO
*  REPRESENTATIONS OR WARRANTIES, EITHER EXPRESSLY OR IMPLIEDLY, ABOUT THE
*  SUITABILITY OR NON-INFRINGEMENT OF THE SOFTWARE. NCS SHALL NOT BE LIABLE
*  FOR ANY LOSSES OR DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
*  MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*
*  =========================================================================
*/
/**
 * Created by xulu on 25/05/2018.
 */
export const APPLICATION_FLOATTAB_INIT = "APPLICATION_FLOATTAB/INIT";
export const APPLICATION_FLOATTAB_SET = "APPLICATION_FLOATTAB/SET";
export const APPLICATION_FLOATTAB_CHANGETAB = "APPLICATION_FLOATTAB/CHANGETAB";

export const APPLICATION_FLOATTAB_GETDETAIL = "APPLICATION_FLOATTAB/GETDETAIL";
export const APPLICATION_FLOATTAB_GETDETAIL_SUCCESS = "APPLICATION_FLOATTAB/GETDETAIL_SUCCESS";

export const APPLICATION_FLOATTAB_GETADDRESS_DETAIL = "APPLICATION_FLOATTAB/GETADDRESS_DETAIL";
export const APPLICATION_FLOATTAB_GETADDRESS_DETAIL_SUCCESS = "APPLICATION_FLOATTAB/GETADDRESS_DETAIL_SUCCESS";

export const APPLICATION_FLOATTAB_CREATE_APP = "APPLICATION_FLOATTAB/CREATE_APP";
export const APPLICATION_FLOATTAB_CREATE_APP_SUCCESS = "APPLICATION_FLOATTAB/CREATE_APP_SUCCESS";

export const APPLICATION_FLOATTAB_UPDATE_APP = "APPLICATION_FLOATTAB/UPDATE_APP";
export const APPLICATION_FLOATTAB_UPDATE_APP_SUCCESS = "APPLICATION_FLOATTAB/UPDATE_APP_SUCCESS";

export const FLOATTAB_GETAPP_SCHEMA_REQUEST = "APPLICATION_FLOATTAB/GETAPP_SCHEMA_REQUEST";
export const FLOATTAB_GETAPP_SCHEMA_SUCCESS = "APPLICATION_FLOATTAB/GETAPP_SCHEMA_SUCCESS";

// export const APPLICATION_FLOATTAB_GETALARM = "APPLICATION_FLOATTAB/GETALARM";
// export const APPLICATION_FLOATTAB_GETALARM_SUCCESS = "APPLICATION_FLOATTAB/GETALARM_SUCCESS";

// export const APPLICATION_FLOATTAB_GETEVENT = "APPLICATION_FLOATTAB/GETEVENT";
// export const APPLICATION_FLOATTAB_GETEVENT_SUCCESS = "APPLICATION_FLOATTAB/GETEVENT_SUCCESS";

export const APPLICATION_FLOATTAB_DETAIL_SEARCH = "APPLICATION_FLOATTAB/DETAIL_SEARCH";

export const APPLICATION_GETDATA_FAILURE = "APPLICATION_FLOATTAB/GETDATA_FAILURE";

export const APPLICATION_FLOATTAB_SET_TITLE = "APPLICATION_FLOATTAB/SET_TITLE";

export const APPLICATION_CREATE_LOCATION_REQUEST = "APPLICATION_FLOATTAB/APPLICATION_CREATE_LOCATION_REQUEST";
export const APPLICATION_CREATE_LOCATION_SUCCESS = "APPLICATION_FLOATTAB/APPLICATION_CREATE_LOCATION_SUCCESS";
export const APPLICATION_CREATE_LOCATION_FAILURE = "APPLICATION_FLOATTAB/APPLICATION_CREATE_LOCATION_FAILURE";

export const APPLICATION_GET_DEVICE_DETAIL_REQUEST = "APPLICATION_FLOATTAB/APPLICATION_GET_DEVICE_DETAIL_REQUEST";
export const APPLICATION_GET_DEVICE_DETAIL_SUCCESS = "APPLICATION_FLOATTAB/APPLICATION_GET_DEVICE_DETAIL_SUCCESS";
export const APPLICATION_GET_DEVICE_DETAIL_FAILURE = "APPLICATION_FLOATTAB/APPLICATION_GET_DEVICE_DETAIL_FAILURE";

export const APPLICATION_UPLOAD_IMAGE_REQUEST = "APPLICATION_FLOATTAB/APPLICATION_UPLOAD_IMAGE_REQUEST";
export const APPLICATION_UPLOAD_IMAGE_SUCCESS = "APPLICATION_FLOATTAB/APPLICATION_UPLOAD_IMAGE_SUCCESS";
export const APPLICATION_UPLOAD_IMAGE_FAILURE = "APPLICATION_FLOATTAB/APPLICATION_UPLOAD_IMAGE_FAILURE";