/*
* =========================================================================
*  Copyright (C)2018 NCS Pte. Ltd. All Rights Reserved
*
*  This software is confidential and proprietary to NCS Pte. Ltd. You shall
*  use this software only in accordance with the terms of the license
*  agreement you entered into with NCS.  No aspect or part or all of this
*  software may be reproduced, modified or disclosed without full and
*  direct written authorisation from NCS.
*
*  NCS SUPPLIES THIS SOFTWARE ON AN "AS IS" BASIS. NCS MAKES NO
*  REPRESENTATIONS OR WARRANTIES, EITHER EXPRESSLY OR IMPLIEDLY, ABOUT THE
*  SUITABILITY OR NON-INFRINGEMENT OF THE SOFTWARE. NCS SHALL NOT BE LIABLE
*  FOR ANY LOSSES OR DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
*  MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*
*  =========================================================================
*/
/**
 * Created by Jia Luo on 27/07/2018.
 */
export const SECURITY_USER_GET_REQUEST = "SECURITY/USER_GET_REQUEST";
export const SECURITY_USER_GET_REQUEST_SUCCESS = "SECURITY/USER_GET_REQUEST_SUCCESS";
export const SECURITY_USER_POST_REQUEST = "SECURITY/USER_POST_REQUEST";
export const SECURITY_USER_POST_REQUEST_SUCCESS = "SECURITY/USER_POST_REQUEST_SUCCESS";
export const SECURITY_USER_PUT_REQUEST = "SECURITY/USER_PUT_REQUEST";
export const SECURITY_USER_PUT_REQUEST_SUCCESS = "SECURITY/USER_PUT_REQUEST_SUCCESS";
export const SECURITY_USER_DELETE_REQUEST = "SECURITY/USER_DELETE_REQUEST";
export const SECURITY_USER_DELETE_REQUEST_SUCCESS = "SECURITY/USER_DELETE_REQUEST_SUCCESS";

export const SECURITY_USER_SELECT = "SECURITY/USER_SELECT";

export const SECURITY_USER_LOADING = "SECURITY/USER_LOADING";

export const SECURITY_USER_SEARCHDATA = "SECURITY/USER_SEARCHDATA";

export const SECURITY_USER_RESET_PASSWORD = "SECURITY/USER_RESET_PASSWORD";

export const SECURITY_USER_RESET = "SECURITY/USER_RESET";

export const SECURITY_USER_GET_GROUP_REQUEST = "SECURITY_USER_GET_GROUP_REQUEST";

export const SECURITY_USER_GET_GROUP_REQUEST_SUCCESS = "SECURITY/USER_GET_GROUP_REQUEST_SUCCESS";

export const SECURITY_USER_GET_FROM_ID_REQUEST = "SECURITY/USER_GET_FROM_ID_REQUEST";
export const SECURITY_USER_GET_FROM_ID_REQUEST_SUCCESS = "SECURITY/USER_GET_FROM_ID_REQUEST_SUCCESS";

export const SECURITY_USER_GET_AVATOR_REQUEST = "SECURITY/USER_GET_AVATOR_REQUEST";
export const SECURITY_USER_GET_AVATOR_REQUEST_SUCCESS = "SECURITY/USER_GET_AVATOR_REQUEST_SUCCESS";

// send email
export const SECURITY_USER_POST_SEND_EMAIL = "SECURITY/USER_POST_SEND_EMAIL";
