/*
 * =========================================================================
 *  Copyright (C)2015 NCS Pte. Ltd. All Rights Reserved
 *
 *  This software is confidential and proprietary to NCS Pte. Ltd. You shall
 *  use this software only in accordance with the terms of the license
 *  agreement you entered into with NCS.  No aspect or part or all of this
 *  software may be reproduced, modified or disclosed without full and
 *  direct written authorisation from NCS.
 *
 *  NCS SUPPLIES THIS SOFTWARE ON AN "AS IS" BASIS. NCS MAKES NO
 *  REPRESENTATIONS OR WARRANTIES, EITHER EXPRESSLY OR IMPLIEDLY, ABOUT THE
 *  SUITABILITY OR NON-INFRINGEMENT OF THE SOFTWARE. NCS SHALL NOT BE LIABLE
 *  FOR ANY LOSSES OR DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
 *  MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 *  =========================================================================
 */
/**
 * Created by @Luo Jia alex on 29/05/15.
 */
export const DASHBOARD_ADD = "DASHBOARD/ADD";
export const DASHBOARD_EDIT = "DASHBOARD/EDIT";
export const DASHBOARD_EDIT_SUCCESS = "DASHBOARD/EDIT/SUCCESS";
export const DASHBOARD_REFRESH_TITLE = "DASHBOARD/REFRESH/TITLE";
export const DASHBOARD_FILTER = "DASHBOARD/FILTER";
export const DASHBOARD_SET_PAGEKEY = "DASHBOARD/SET/PAGEKEY";

export const DASHBOARD_GET_SUCCESS = "DASHBOARD/GET/SUCCESS";
export const DASHBOARD_GET = "DASHBOARD/GET";
export const DASHBOARD_ADD_SUCCESS = "DASHBOARD/ADD/SUCCESS";

export const DASHBOARD_DELETE = "DASHBOARD/DELETE";
export const DASHBOARD_DUPLICATE = "DASHBOARD/DUPLICATE";
export const DASHBOARD_DELETE_SUCCESS = "DASHBOARD/DELETE/SUCCESS";
export const DASHBOARD_DELETE_REQUEST = "DASHBOARD/DELET/REQUEST";

export const DASHBOARD_REQUEST = "DASHBOARD/REQUEST";
export const DASHBOARD_REQUEST_SUCCESS = "REQUEST/DASHBOARD/SUCCESS";

export const WIDGET_ADD = "WIDGET/ADD";
export const WIDGET_SAVE = "WIDGET/SAVE";
export const WIDGET_SAVE_SUCCESS = "WIDGET_SAVE/SUCCESS";

export const TOOGLE_SCALE = "TOOGLE/SCALE";
export const REST_CURRITEM = "REST/CURRITEM";
export const REST_DASHBOARD_ITEM = "REST/DASHBOARD/ITEM";

// splite line
// GROUP ACTION TYPE
export const GROUP_ADD_REQUEST = "GROUP/ADD/REQUEST";
export const GROUP_ADD_REQUEST_SUCCESS = "GROUP/ADD/REQUEST/SUCCESS";
export const GROUP_REQUEST_SUCCESS = "GROUP/REQUEST/SUCCESS";
export const GROUP_EDIT_REQUEST = "GROUP/EDIT/REQUEST";
export const GROUP_EDIT_REQUEST_SUCCESS = "GROUP/EDIT/REQUEST/SUCCESS";
export const GROUP_DELETE_REQUEST = "GROUP/DELETE/REQUEST";
export const GROUP_DELETE_REQUEST_SUCCESS = "GROUP/DELETE/REQUEST/SUCCESS";
export const GROUPLIST_UPDATE_REQUEST = "GROUPLIST/UPDATE/REQUEST";

// MOVE TO ACTION TYPE
export const DASHBOARD_GROUP_REQUEST_SUCCESS = "DASHBOARD/GROUP/REQUEST/SUCCESS";
export const DASHBOARD_GROUP_REQUEST = "DASHBOARD/GROUP/REQUEST";

export const DASHBOARD_GROUP_DELETE_REQUEST = "DASHBOARD/GROUP/DELETE/REQUEST";
export const DASHBOARD_GROUP_DELETE_REQUEST_SUCCESS = "DASHBOARD/GROUP/DELETE/REQUEST/SUCCESS";

export const DASHBOARD_GROUP_EDIT_REQUEST = "DASHBOARD/GROUP/EDIT/REQUEST";
export const DASHBOARD_GROUP_EDIT_REQUEST_SUCCESS = "DASHBOARD/GROUP/EDIT/REQUEST/SUCCESS";

export const DASHBOARD_GROUP_FILTER = "DASHBOARD/GROUP/FILTER";

export const DASHBOARD_GROUP_PUSH_ITEM = "DASHBOARD/GROUP/PUSH/ITEM";

// DUPLICATE ACTION TYPE
export const DASHBOARD_DUPLICATE_REQUEST = "DASHBOARD/DUPLICATE/REQUEST";
export const DASHBOARD_DUPLICATE_REQUEST_SUCCESS = "DASHBOARD/DUPLICATE/REQUEST/SUCCESS";

// NEW DASHBOARD
export const DASHBOARD_ADD_REQUEST = "DASHBOARD/ADD/REQUEST";
export const DASHBOARD_ADD_REQUEST_SUCCESS = "DASHBOARD/ADD/REQUEST/SUCCESS";
export const DASHBOARD_TEMPLATE_REQUEST = "DASHBOARD/TEMPLATE/REQUEST";
export const DASHBOARD_TEMPLATE_REQUEST_SUCCESS = "DASHBOARD/TEMPLATE/REQUEST/SUCCESS";

// SEARCH ACTION TYPE
export const SEARCH_REQUEST = "SEARCH/REQUEST";
export const SEARCH_REQUEST_SUCCESS = "SEARCH/REQUEST/SUCCESS";

// count
export const COUNT_REQUEST = "COUNT_REQUEST";
export const COUNT_REQUEST_SUCCESS = "COUNT/REQUEST/SUCCESS";

// TEMPLATE ACTION TYPE
export const TEMPLATE_SAVE_REQUEST = "TEMPLATE/SAVE/REQUEST";
export const TEMPLATE_SAVE_REQUEST_SUCCESS = "TEMPLATE/SAVE/REQUEST/SUCCESS";
export const TEMPLATE_DELETE_REQUEST = "TEMPLATE/DELETE_REQUEST";

// cheak user modify
export const CCMS_DASHBOARD_LIBRARY_CHECK_USER_MODIFY = "CCMS/DASHBOARD_LIBRARY_CHECK_USER_MODIFY";
export const CCMS_DASHBOARD_LIBRARY_CLEAN_TOKEN_FOR_PAGE = "CCMS/DASHBOARD_LIBRARY_CLEAN_TOKEN_FOR_PAGE";

// toggle loading cover
export const DDASHBOARD_LOADING_COVER = "DASHBOARD/LOADING_COVER";
// update page priority
export const DASHBOARD_PAGE_PRIORITY = "DASHBOARD/PAGE_PRIORITY";
// get applications by group
export const DASHBOARD_APPLICATION_BY_TYPE = "DASHBOARD/APPLICATION_BY_TYPE";
// get thumbnail
export const DASHBOARD_GET_THUMBNAIL_BY_FILEID = "DASHBOARD/GET_THUMBNAIL_BY_FILEID";
// get thumbnail success
export const DASHBOARD_GET_THUMBNAIL_SUCCESS = "DASHBOARD/GET_THUMBNAIL_SUCCESS";
export const DASHBOARD_GET_CUSTOMIZED_DASHBOARDS = "DASHBOARD/GET_CUSTOMIZED_DASHBOARDS";
export const DASHBOARD_GET_CUSTOMIZED_DASHBOARD_KEY = "DASHBOARD/GET_CUSTOMIZED_DASHBOARD_KEY";
