/*
 * =========================================================================
 *  Copyright (C)2018 NCS Pte. Ltd. All Rights Reserved
 *
 *  This software is confidential and proprietary to NCS Pte. Ltd. You shall
 *  use this software only in accordance with the terms of the license
 *  agreement you entered into with NCS.  No aspect or part or all of this
 *  software may be reproduced, modified or disclosed without full and
 *  direct written authorisation from NCS.
 *
 *  NCS SUPPLIES THIS SOFTWARE ON AN "AS IS" BASIS. NCS MAKES NO
 *  REPRESENTATIONS OR WARRANTIES, EITHER EXPRESSLY OR IMPLIEDLY, ABOUT THE
 *  SUITABILITY OR NON-INFRINGEMENT OF THE SOFTWARE. NCS SHALL NOT BE LIABLE
 *  FOR ANY LOSSES OR DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
 *  MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 *  =========================================================================
 */
/**
 * Created by wplei on 25/05/18.
 */
export const CCMS_WIDGETS_BOARD_TOGGLE_EDIT_MODE = "CCMS/WIDGETS_BOARD_TOGGLE_EDIT_MODE";

export const CCMS_WIDGETS_BOARD_PREVIEW_CENTRE_ELEMENT_SWITCH = "CCMS/WIDGETS_BOARD_PREVIEW_CENTRE_ELEMENT_SWITCH";

export const CCMS_WIDGETS_BOARD_PAGECONFIG_REQUEST = "CCMS/WIDGETS_BOARD_PAGECONFIG_REQUEST";

export const CCMS_WIDGETS_BOARD_PAGECONFIG_REQUEST_RESULT = "CCMS/WIDGETS_BOARD_PAGECONFIG_REQUEST_RESULT";

export const CCMS_WIDGETS_BOARD_UPDATE_PAGECONFIG_REQUEST = "CCMS/WIDGETS_BOARD_UPDATE_PAGECONFIG_REQUEST";

export const CCMS_WIDGETS_BOARD_UPDATE_REDUCER_PAGECONFIG = "CCMS/WIDGETS_BOARD_UPDATE_REDUCER_PAGECONFIG";

export const CCMS_WIDGETS_BOARD_REQUEST_ALL_DEFAULT_COMPONENT = "CCMS/WIDGETS_BOARD_REQUEST_ALL_DEFAULT_COMPONENT";

export const CCMS_WIDGETS_BOARD_TRANSMIT_DEFAULT_COMPONENTS = "CCMS/WIDGETS_BOARD_TRANSMIT_DEFAULT_COMPONENTS";

export const CCMS_WIDGETS_BOARD_SAVE_TEMPLATE = "CCMS/WIDGETS_BOARD_SAVE_TEMPLATE_QWER";

export const CCMS_WIDGETS_BOARD_EXPORT_WIDGETS = "CCMS/WIDGETS_BOARD_EXPORT_WIDGETS";

export const CCMS_WIDGETS_BOARD_ERROR_MESSAGE = "CCMS/WIDGETS_BOARD_ERROR_MESSAGE";

export const CCMS_WIDGETS_BOARD_LOADING_STATUS = "CCMS/WIDGETS_BOARD_LOADING_STATUS";

export const CCMS_DASHBOARD_LIBRARY_CLEAN_TOKEN_FOR_PAGE = "CCMS/DASHBOARD_LIBRARY_CLEAN_TOKEN_FOR_PAGE";
// create & update & get resource
export const CCMS_WIDGET_BOARD_CREATE_AND_UPDATE_RESOURCE = "CCMS/WIDGET_BOARD_CREATE_AND_UPDATE_RESOURCE";
export const CCMS_WIDGET_BOARD_GET_RESOURCE_BY_GROUP_AND_RESOURCEID =
    "CCMS/WIDGET_BOARD_GET_RESOURCE_BY_GROUP_AND_RESOURCEID";

// page editable
export const CCMS_WIDGET_BOARD_EDITABLE = "CCMS/WIDGET_BOARD_EDITABLE";
// getPermissionList
export const CCMS_WIDGET_BOARD_GET_PERMISSION_LIST = "CCMS/WIDGET_BOARD_GET_PERMISSION_LIST";
//update permission list
export const CCMS_WIDGET_BOARD_UPDATE_PERMISSION_LIST = "CCMS/WIDGET_BOARD_UPDATE_PERMISSION_LIST";
// toggle security dialog
export const CCMS_WIDGET_BOARD_TOGGLE_SECURITY_DIALOG = "CCMS/WIDGET_BOARD_TOGGLE_SECURITY_DIALOG";
// get resource info
export const CCMS_WIDGET_BOARD_GET_RESOURCE_INFOMATION = "CCMS/WIDGET_BOARD_GET_RESOURCE_INFOMATION";
// pass permission list
export const CCMS_WIDGET_BOARD_PASS_PERMISSION_LIST = "CCMS/WIDGET_BOARD_PASS_PERMISSION_LIST";
// delete resourceid
export const CCMS_DASHBOARD_LIBRARY_DELETE_RESOURCE = "CCMS/DASHBOARD_LIBRARY_DELETE_RESOURCE";
// pass resource detail
export const CCMS_DASHBOARD_LIBRARY_PASSRESOURCE_DETAIL = "CCMS/DASHBOARD_LIBRARY_PASSRESOURCE_DETAIL";
// toggle all modals
export const CCMS_DAHSBOARD_MODAL_STATUS_CONTROL = "CCMS/DAHSBOARD_MODAL_STATUS_CONTROL";
export const CCMS_DASHBOARD_CHECK_VISUAL = "CCMS/DASHBOARD_CHECK_VISUAL";
