export const BASE_HEADER_TITLE = "HEADER/BASE_HEADER_TITLE";

export const BASE_HEADER_USER_GET_AVATOR_REQUEST = "BASE_HEADER/USER_GET_AVATOR_REQUEST";
export const BASE_HEADER_GET_AVATOR_REQUEST_SUCCESS = "BASE_HEADER/USER_GET_AVATOR_REQUEST_SUCCESS";

export const BASE_HEADER_USER_GET_LOGO_REQUEST = "BASE_HEADER/USER_GET_LOGO_REQUEST";
export const BASE_HEADER_GET_LOGO_REQUEST_SUCCESS = "BASE_HEADER/USER_GET_LOGO_REQUEST_SUCCESS";

export const BASE_HEADER_RESET = "BASE_HEADER_RESET";
