export const ACCOUNT_LIST_REQUEST = "ACCOUNT/LIST_REQUEST";
export const ACCOUNT_LIST_REQUEST_SUCCESS = "ACCOUNT/LIST_REQUEST_SUCCESS";

export const ACCOUNT_ITEM_REQUEST = "ACCOUNT/ITEM_REQUEST";
export const ACCOUNT_ITEM_REQUEST_SUCCESS = "ACCOUNT/ITEM_REQUEST_SUCCESS";

export const ACCOUNT_UPDATE_REQUEST = "ACCOUNT/UPDATE_REQUEST";
export const ACCOUNT_UPDATE_REQUEST_SUCCESS = "ACCOUNT/UPDATE_REQUEST_SUCCESS";

export const ACCOUNT_SAVE_REQUEST = "ACCOUNT/SAVE_REQUEST";
export const ACCOUNT_SAVE_REQUEST_SUCCESS = "ACCOUNT/SAVE_REQUEST_SUCCESS";

export const ACCOUNT_DELETE_REQUEST = "ACCOUNT/DELETE_REQUEST";
export const ACCOUNT_DELETE_REQUEST_SUCCESS = "ACCOUNT/DELETE_REQUEST_SUCCESS";

export const ACCOUNT_RESET = "ACCOUNT/RESET";

// obsolete
export const ACCOUNT_SAVE_URL_TO_SYS = "ACCOUNT/SAVE_URL_TO_SYS";
export const ACCOUNT_UPDATE_URL_IN_SYS = "ACCOUNT/UPDATE_URL_IN_SYS";
// obsolete
export const ACCOUNT_URL_REQUEST = "ACCOUNT/URL_REQUEST";

// get account group list
export const ACCOUNT_GROUP_REQUEST = "ACCOUNT/GROUP_REQUEST";
export const ACCOUNT_GROUP_REQUEST_SUCCESS = "ACCOUNT/GROUP_REQUEST_SUCCESS";
// save account group
export const ACCOUNT_GROUP_SAVE_REQUEST = "ACCOUNT/GROUP_SAVE_REQUEST";
export const ACCOUNT_GROUP_SAVE_REQUEST_SUCCESS = "ACCOUNT/GROUP_SAVE_REQUEST_SUCCESS";

// GET LOG
export const ACCOUNT_GET_LOGO_REQUEST = "ACCOUNT/GET_LOGO_REQUEST";
export const ACCOUNT_GET_LOGO_REQUEST_SUCCESS = "ACCOUNT/GET_LOGO_REQUEST_SUCCESS";
